### ISSUE TITLE
Menubar says NewApplication instead of "Portfolio Performance"

### ISSUE THREAD

**Issue by chrisaut** [portfolio-performance/portfolio#3666] opened 2023-11-26 12:59 UTC
**Describe the bug**
On MacOS 14.0, with a Macbook Air M1, the Menubar says NewApplication instead of "Portfolio Performance"
Note I only use the Macbook while on the road, at home I use the Windows versions so I'm unsure how long this has been going on.

**To Reproduce**
1. Simply launch the application

**Expected behavior**
It should say Portfolio Performance

**Screenshots**
<img width="451" alt="image" src="https://github.com/portfolio-performance/portfolio/assets/8252355/a383bbe9-2b9b-4038-b3f3-94c1bb1f6ee1">

**Desktop (please complete the following information):**
 - OS: MacOS 14.0
 - Version: 0.65.6 (Nov 2023)
Platform: macosx, aarch64
Java: 17.0.5+8-LTS, Azul Systems, Inc.

**Comment by chirlu** [comment] 2023-11-26 13:43
Duplicate of #3595, and not our bug; fixed in MacOS Sonoma 14.1.

**Closed by chirlu** 2023-11-26 13:43 UTC
Labels: bug
