### ISSUE TITLE
Stock split feature yields exceptions

### ISSUE THREAD

**Issue by JTinkers** [portfolio-performance/portfolio#2593] opened 2021-12-22 18:34 UTC
**Describe the bug**
$NAKD has just split in 1:15 ratio (new:old).
Using the method yields the errors below.

**To Reproduce**
1. Add a purchase of say.. 1018 $NAKD for 0.45$
2. Try doing the 1 to 15 split
3. Exception pops

**Expected behavior**
Transactions to update without an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/30983493/147139195-eac24b65-5f01-413f-b30a-614a0f7d7650.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.56.2

**Comment by JTinkers** [comment] 2021-12-23 09:41
Here's details:
![image](https://user-images.githubusercontent.com/30983493/147221245-8a199a50-0150-44c0-9bdb-fa66f4abe967.png)

**Comment by OnkelDok** [comment] 2021-12-23 11:20
Duplicate of #2581

**Comment by Nirus2000** [comment] 2023-08-10 19:13
this issue is fixes with [239db78](https://github.com/portfolio-performance/portfolio/commit/239db78483d84ad82745fc81ace8f6975d7d791c)

**Closed by Nirus2000** 2023-08-10 19:13 UTC
Labels: bug
